In [17]:
from sklearn.datasets import load_boston
from sklearn.neighbors import KNeighborsRegressor
import numpy as np

In [33]:
boston = load_boston()
print(boston.data)
print(boston.target)

[[6.3200e-03 1.8000e+01 2.3100e+00 ... 1.5300e+01 3.9690e+02 4.9800e+00]
 [2.7310e-02 0.0000e+00 7.0700e+00 ... 1.7800e+01 3.9690e+02 9.1400e+00]
 [2.7290e-02 0.0000e+00 7.0700e+00 ... 1.7800e+01 3.9283e+02 4.0300e+00]
 ...
 [6.0760e-02 0.0000e+00 1.1930e+01 ... 2.1000e+01 3.9690e+02 5.6400e+00]
 [1.0959e-01 0.0000e+00 1.1930e+01 ... 2.1000e+01 3.9345e+02 6.4800e+00]
 [4.7410e-02 0.0000e+00 1.1930e+01 ... 2.1000e+01 3.9690e+02 7.8800e+00]]
[24.  21.6 34.7 33.4 36.2 28.7 22.9 27.1 16.5 18.9 15.  18.9 21.7 20.4
 18.2 19.9 23.1 17.5 20.2 18.2 13.6 19.6 15.2 14.5 15.6 13.9 16.6 14.8
 18.4 21.  12.7 14.5 13.2 13.1 13.5 18.9 20.  21.  24.7 30.8 34.9 26.6
 25.3 24.7 21.2 19.3 20.  16.6 14.4 19.4 19.7 20.5 25.  23.4 18.9 35.4
 24.7 31.6 23.3 19.6 18.7 16.  22.2 25.  33.  23.5 19.4 22.  17.4 20.9
 24.2 21.7 22.8 23.4 24.1 21.4 20.  20.8 21.2 20.3 28.  23.9 24.8 22.9
 23.9 26.6 22.5 22.2 23.6 28.7 22.6 22.  22.9 25.  20.6 28.4 21.4 38.7
 43.8 33.2 27.5 26.5 18.6 19.3 20.1 19.5 19.5 20.4 19.8 19.

In [15]:
from sklearn.preprocessing import scale
data_scaled = scale(boston.data)
print(data_scaled)

[[-0.41978194  0.28482986 -1.2879095  ... -1.45900038  0.44105193
  -1.0755623 ]
 [-0.41733926 -0.48772236 -0.59338101 ... -0.30309415  0.44105193
  -0.49243937]
 [-0.41734159 -0.48772236 -0.59338101 ... -0.30309415  0.39642699
  -1.2087274 ]
 ...
 [-0.41344658 -0.48772236  0.11573841 ...  1.17646583  0.44105193
  -0.98304761]
 [-0.40776407 -0.48772236  0.11573841 ...  1.17646583  0.4032249
  -0.86530163]
 [-0.41500016 -0.48772236  0.11573841 ...  1.17646583  0.44105193
  -0.66905833]]


In [19]:
param = np.linspace(1, 10, 200)
print(param)

[ 1.          1.04522613  1.09045226  1.13567839  1.18090452  1.22613065
  1.27135678  1.31658291  1.36180905  1.40703518  1.45226131  1.49748744
  1.54271357  1.5879397   1.63316583  1.67839196  1.72361809  1.76884422
  1.81407035  1.85929648  1.90452261  1.94974874  1.99497487  2.04020101
  2.08542714  2.13065327  2.1758794   2.22110553  2.26633166  2.31155779
  2.35678392  2.40201005  2.44723618  2.49246231  2.53768844  2.58291457
  2.6281407   2.67336683  2.71859296  2.7638191   2.80904523  2.85427136
  2.89949749  2.94472362  2.98994975  3.03517588  3.08040201  3.12562814
  3.17085427  3.2160804   3.26130653  3.30653266  3.35175879  3.39698492
  3.44221106  3.48743719  3.53266332  3.57788945  3.62311558  3.66834171
  3.71356784  3.75879397  3.8040201   3.84924623  3.89447236  3.93969849
  3.98492462  4.03015075  4.07537688  4.12060302  4.16582915  4.21105528
  4.25628141  4.30150754  4.34673367  4.3919598   4.43718593  4.48241206
  4.52763819  4.57286432  4.61809045  4.66331658  4

In [24]:
from sklearn.model_selection import KFold, cross_val_score

In [44]:
mean = []
X = np.array(data_scaled)
y = boston.target
print(X)
kf = KFold(shuffle = True, random_state = 42)
for i in param:
    dtc = KNeighborsRegressor(n_neighbors = 5, weights = 'distance', p = i)
    r = cross_val_score(dtc, X, y, cv=kf, scoring='neg_mean_squared_error')
    mean.append(r.mean())
print(mean)
result = mean.index(max(mean)) + 1
f = open('results.txt', 'w')
f.write(str(result))

[[-0.41978194  0.28482986 -1.2879095  ... -1.45900038  0.44105193
  -1.0755623 ]
 [-0.41733926 -0.48772236 -0.59338101 ... -0.30309415  0.44105193
  -0.49243937]
 [-0.41734159 -0.48772236 -0.59338101 ... -0.30309415  0.39642699
  -1.2087274 ]
 ...
 [-0.41344658 -0.48772236  0.11573841 ...  1.17646583  0.44105193
  -0.98304761]
 [-0.40776407 -0.48772236  0.11573841 ...  1.17646583  0.4032249
  -0.86530163]
 [-0.41500016 -0.48772236  0.11573841 ...  1.17646583  0.44105193
  -0.66905833]]
[-16.030646734221644, -16.40783870832999, -16.370696947059045, -16.445716308439433, -16.475057773399403, -16.526432329318258, -16.636709345898257, -16.82422425426731, -16.874209056598744, -17.124898819792115, -17.145231882153887, -17.01936008026763, -17.09913173771377, -16.801326640288362, -16.980745198189776, -17.03345890364771, -17.17164190266228, -17.181679169045047, -17.20826374287096, -17.32368019839837, -17.415118891722805, -17.385662319793234, -17.326038597662453, -17.336966976165666, -17.38264865

1