In [3]:
import numpy as np

import pandas

data = pandas.read_csv('titanic.csv', index_col='PassengerId')
print(data[:10])

             Survived  Pclass  \
PassengerId                     
1                   0       3   
2                   1       1   
3                   1       3   
4                   1       1   
5                   0       3   
6                   0       3   
7                   0       1   
8                   0       3   
9                   1       3   
10                  1       2   

                                                          Name     Sex   Age  \
PassengerId                                                                    
1                                      Braund, Mr. Owen Harris    male  22.0   
2            Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0   
3                                       Heikkinen, Miss. Laina  female  26.0   
4                 Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0   
5                                     Allen, Mr. William Henry    male  35.0   
6                                          

In [4]:
from sklearn.tree import DecisionTreeClassifier

In [6]:
#выделим нужные столбцы
needed=data[['Pclass', 'Fare', 'Age', 'Sex', 'Survived']]

In [7]:
print(needed[:10])

             Pclass     Fare   Age     Sex  Survived
PassengerId                                         
1                 3   7.2500  22.0    male         0
2                 1  71.2833  38.0  female         1
3                 3   7.9250  26.0  female         1
4                 1  53.1000  35.0  female         1
5                 3   8.0500  35.0    male         0
6                 3   8.4583   NaN    male         0
7                 1  51.8625  54.0    male         0
8                 3  21.0750   2.0    male         0
9                 3  11.1333  27.0  female         1
10                2  30.0708  14.0  female         1


In [8]:
#уберем наны
sorted = needed[np.isnan(data['Age']) != True]

In [9]:
print(sorted)

             Pclass     Fare   Age     Sex  Survived
PassengerId                                         
1                 3   7.2500  22.0    male         0
2                 1  71.2833  38.0  female         1
3                 3   7.9250  26.0  female         1
4                 1  53.1000  35.0  female         1
5                 3   8.0500  35.0    male         0
...             ...      ...   ...     ...       ...
886               3  29.1250  39.0  female         0
887               2  13.0000  27.0    male         0
888               1  30.0000  19.0  female         1
890               1  30.0000  26.0    male         1
891               3   7.7500  32.0    male         0

[714 rows x 5 columns]


In [45]:
sorted.loc['Sex', 0] = 'male'

In [55]:
print(sorted.at[1, 'Sex'])

male


In [63]:
#actually it doesn't work
for k in sorted['Sex']:
    if k == 'male':
        k = '1'
    else:
        k = '0'

In [75]:
#and this does
sorted.loc[sorted['Sex'] == 'male', 'Sex'] = 1
sorted.loc[sorted['Sex'] == 'female', 'Sex'] = 0

C:\ProgramData\Anaconda3\lib\site-packages\pandas\core\indexing.py:1720: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self._setitem_single_column(loc, value, pi)


In [76]:
print(sorted['Sex'])

PassengerId
1      1
2      0
3      0
4      0
5      1
      ..
886    0
887    1
888    0
890    1
891    1
Name: Sex, Length: 714, dtype: object


In [100]:
X = np.array([sorted['Pclass'], sorted['Fare'], sorted['Age'], sorted['Sex']])
X_t=X.transpose()
y = np.array(sorted['Survived'])
clf = DecisionTreeClassifier(random_state=241)
clf.fit(X_t, y)

DecisionTreeClassifier(random_state=241)

In [101]:
importances = clf.feature_importances_
print(importances)

[0.14000522 0.30343647 0.2560461  0.30051221]


In [105]:
X_е = np.array(sorted[['Pclass', 'Fare', 'Age', 'Sex']])
print(X)

[[3 1 3 ... 1 1 3]
 [7.25 71.2833 7.925 ... 30.0 30.0 7.75]
 [22.0 38.0 26.0 ... 19.0 26.0 32.0]
 [1 0 0 ... 0 1 1]]


In [11]:
sorted['Pclass'].corr(sorted['Fare'])

-0.5541824708598451